// script
export { uncaughtErrorHandler } from './uncaughtErrorHandler'
export { resourceErrorHandler } from './resourceErrorHandler'
export { unhandledrejectionErrorHandler } from './unhandledrejectionErrorHandler'
export { unknownErrorHandler } from './unknownErrorHandler'
export type { UncaughtErrorDetail } from './uncaughtErrorHandler'
export type { ResourceErrorDetail } from './resourceErrorHandler'
export type { UnhandledrejectionErrorDetail } from './unhandledrejectionErrorHandler'
export type { UnknownErrorDetail } from './unknownErrorHandler'
// network
export { ajaxErrorHandler } from './ajaxErrorHandler'
export { fetchErrorHandler } from './fetchErrorHandler'
export { websocketErrorHandler } from './websocketErrorHandler'
export type { AjaxErrorDetail } from './ajaxErrorHandler'
export type { FetchErrorDetail } from './fetchErrorHandler'
export type { WebsocketErrorDetail } from './websocketErrorHandler'
